[book]
authors = ["vxpm"]
language = "en"
multilingual = false
src = "src"
title = "PSX Notes"

[preprocessor.alerts]

[preprocessor.pagetoc]

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
smart-punctuation = true
git-repository-url = "https://github.com/vxpm/psxnotes"
